baseURL = "https://handbook.airlinesim.aero/"
languageCode = "en-us"
title = "AirlineSim Handbook"
theme = "hugo-book"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  editURL = "https://github.com/simulogics/airlinesim-docs/edit/master/content/"
  # Author of the site, will be used in meta information
  author = ""
  # Description of the site, will be used in meta information
  description = "AirlineSim Handbook"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "AirlineSim Handbook"
weight = 1
languageName = "English"

[Languages.de]
title = "AirlineSim Handbuch"
weight = 2
languageName = "Deutsch"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-edit'></i> Contribute!"
url = "https://github.com/simulogics/airlinesim-docs#how-to-contribute-to-the-documentation"
weight = 99

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-edit'></i> Mitmachen!"
url = "https://github.com/simulogics/airlinesim-docs#how-to-contribute-to-the-documentation"
weight = 99